version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing HTML validator...
      - npm install -g htmlhint

  build:
    commands:
      - echo Checking HTML files for errors...
      - htmlhint "**/*.html"

artifacts:
  files:
    - '**/*'
